service: szarvaspongrac

image: peterszarvas94/szarvaspongrac

servers:
  web:
    - 37.27.206.49

proxy:
  ssl: true
  host: szarvaspongrac.hu

registry:
  username: peterszarvas94

  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  remote: ssh://peti@37.27.206.49

ssh:
  user: "peti"
